テスト実装
nablarch/nablarch-example-rest pull request #23
Opened 2020-05-28 11:07 UTC by kumagoro1202

2020-06-09 08:20 UTC, backpaper0 requested changes

2020-06-09 08:20 UTC, backpaper0 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +            fail(e.getMessage());
わざわざcatchしている理由はありますか？

これだとスタックトレースも消えるし、単にメソッドに`throws Exception`を付けておけば良いと思うのですが。

2020-06-09 08:20 UTC, backpaper0 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +        assertStatusCode(message2, HttpResponse.Status.CREATED.getStatusCode(), registerResponse);
`assertStatusCode`は`getStatusCode`しなくても良いバージョンが欲しくなりますね（つまり`HttpResponse.Status.CREATED`を渡したい）。

2020-06-10 06:59 UTC, kumagoro1202 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +        assertStatusCode(message2, HttpResponse.Status.CREATED.getStatusCode(), registerResponse);
作りながら迷ったんですが、↓に合わせてintにしていました。
https://github.com/nablarch/nablarch-testing/blob/master/src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java#L721
やっぱりあったほうが便利だと思うので作ります。

2020-06-10 07:00 UTC, kumagoro1202 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +        assertStatusCode(message2, HttpResponse.Status.CREATED.getStatusCode(), registerResponse);
https://github.com/nablarch/nablarch-testing-rest/pull/1/commits/b7d8d296be36eadddde88cd98e35e7ec8f0398d8

2020-06-10 08:08 UTC, kumagoro1202 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +        assertStatusCode(message2, HttpResponse.Status.CREATED.getStatusCode(), registerResponse);
https://github.com/nablarch/nablarch-example-rest/pull/23/commits/b32401b98065c4acf6522f17221ca5e107f8933f

2020-06-10 08:08 UTC, kumagoro1202 commented on src/test/java/com/nablarch/example/action/ProjectActionTest.java
> +            fail(e.getMessage());
https://github.com/nablarch/nablarch-example-rest/pull/23/commits/b32401b98065c4acf6522f17221ca5e107f8933f#diff-a81ecbc39df2bab4be21b0515a460063R30

2020-06-11 00:52 UTC, backpaper0 approved these changes

2020-06-19 04:47 UTC, merged